
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.DropMode;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import uk.co.caprica.vlcj.binding.LibVlc;
import uk.co.caprica.vlcj.component.EmbeddedMediaPlayerComponent;
import uk.co.caprica.vlcj.player.MediaPlayer;
import uk.co.caprica.vlcj.player.MediaPlayerEventAdapter;
import uk.co.caprica.vlcj.player.MediaPlayerFactory;
import uk.co.caprica.vlcj.player.embedded.DefaultFullScreenStrategy;
import uk.co.caprica.vlcj.player.embedded.EmbeddedMediaPlayer;
import uk.co.caprica.vlcj.runtime.RuntimeUtil;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Acer 4738
 */
public class VideoPlayer extends javax.swing.JFrame {

    /**
     * Creates new form VideoPlayer
     */
    public VideoPlayer() {
        initComponents();
//        setUndecorated(true);
//        this.setOpacity((float)0.5);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane2 = new javax.swing.JDesktopPane();
        canvas1 = new java.awt.Canvas();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListSong = new javax.swing.JList<>();
        LayerPlayAnBtn = new javax.swing.JLayeredPane();
        btnStereo = new javax.swing.JButton();
        SlicePlaying = new javax.swing.JSlider();
        btnRight = new javax.swing.JButton();
        SlideVolumn = new javax.swing.JSlider();
        btnLeft = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();
        btnAddSong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jDesktopPane2.setLayout(new java.awt.BorderLayout());

        canvas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                canvas1MouseClicked(evt);
            }
        });
        canvas1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                canvas1MouseMoved(evt);
            }
        });
        jDesktopPane2.add(canvas1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new javax.swing.OverlayLayout(jPanel1));

        ListSong.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                ListSongMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ListSongMouseMoved(evt);
            }
        });
        ListSong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListSongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListSong);

        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        LayerPlayAnBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LayerPlayAnBtnMouseEntered(evt);
            }
        });

        btnStereo.setText("Stereo");

        SlicePlaying.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                SlicePlayingMouseDragged(evt);
            }
        });
        SlicePlaying.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SlicePlayingMouseReleased(evt);
            }
        });

        btnRight.setText("Right");

        SlideVolumn.setOrientation(javax.swing.JSlider.VERTICAL);

        btnLeft.setText("Left");

        btnPlay.setText("Play");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnAddSong.setText("Add");
        btnAddSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSongActionPerformed(evt);
            }
        });

        LayerPlayAnBtn.setLayer(btnStereo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayerPlayAnBtn.setLayer(SlicePlaying, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayerPlayAnBtn.setLayer(btnRight, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayerPlayAnBtn.setLayer(SlideVolumn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayerPlayAnBtn.setLayer(btnLeft, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayerPlayAnBtn.setLayer(btnPlay, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayerPlayAnBtn.setLayer(btnAddSong, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout LayerPlayAnBtnLayout = new javax.swing.GroupLayout(LayerPlayAnBtn);
        LayerPlayAnBtn.setLayout(LayerPlayAnBtnLayout);
        LayerPlayAnBtnLayout.setHorizontalGroup(
            LayerPlayAnBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayerPlayAnBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LayerPlayAnBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LayerPlayAnBtnLayout.createSequentialGroup()
                        .addComponent(btnStereo)
                        .addGap(18, 18, 18)
                        .addComponent(btnRight)
                        .addGap(18, 18, 18)
                        .addComponent(btnLeft)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddSong))
                    .addGroup(LayerPlayAnBtnLayout.createSequentialGroup()
                        .addComponent(btnPlay)
                        .addGap(18, 18, 18)
                        .addComponent(SlicePlaying, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(SlideVolumn, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        LayerPlayAnBtnLayout.setVerticalGroup(
            LayerPlayAnBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayerPlayAnBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LayerPlayAnBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LayerPlayAnBtnLayout.createSequentialGroup()
                        .addGroup(LayerPlayAnBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnStereo)
                            .addComponent(btnRight)
                            .addComponent(btnLeft)
                            .addComponent(btnAddSong))
                        .addGap(14, 14, 14)
                        .addGroup(LayerPlayAnBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPlay)
                            .addComponent(SlicePlaying, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 43, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LayerPlayAnBtnLayout.createSequentialGroup()
                        .addComponent(SlideVolumn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(535, 535, 535)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LayerPlayAnBtn))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDesktopPane2)
                    .addComponent(jLayeredPane1))
                .addGap(0, 0, 0)
                .addComponent(LayerPlayAnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(699, 521));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    //DefaultListModel<Object>
    private ArrayList<File> arraySong=new ArrayList<>();    
    DefaultListModel<String> mod;
    
    private void initVlcLibAndPlayer(){
        
        mpf = new MediaPlayerFactory();
        player = mpf.newEmbeddedMediaPlayer();
        player.setVideoSurface(mpf.newVideoSurface(canvas1));
        player.setEnableKeyInputHandling(false);
        player.setEnableMouseInputHandling(false);
        player.addMediaPlayerEventListener(new MediaPlayerEventAdapter(){
            @Override
            public void lengthChanged(MediaPlayer mediaPlayer, long newLength) {
                SlicePlaying.setMaximum((int)newLength);
            }

            @Override
            public void timeChanged(MediaPlayer mediaPlayer, long newTime) {
                SlicePlaying.setValue((int)newTime);
            }

            @Override
            public void stopped(MediaPlayer mediaPlayer) {
                
                
            }
            
            
        
        });
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       mod=new DefaultListModel<>();
       ListSong.setModel(mod);
       ListSong.setDragEnabled(true);
       ListSong.setTransferHandler(new MyTransferHandler());
       ListSong.setDropMode(DropMode.INSERT);
       NativeLibrary.addSearchPath(RuntimeUtil.getLibVlcLibraryName(), "C:\\Program Files\\VideoLAN\\VLC");
        Native.loadLibrary(RuntimeUtil.getLibVlcLibraryName(), LibVlc.class);
        
        initVlcLibAndPlayer();      
       
       
    }//GEN-LAST:event_formWindowOpened
    
    MediaPlayerFactory mpf;
    DefaultFullScreenStrategy fs;
    EmbeddedMediaPlayer player;
    File f;
    boolean b=false;
    
    private void canvas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvas1MouseClicked
        
        if(evt.getClickCount()==2){  
            long time=player.getTime();
            if (b==false) {
                b=true;
                jLayeredPane1.setVisible(false);
                LayerPlayAnBtn.setVisible(false);
                this.dispose();
                setUndecorated(true);
                GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().setFullScreenWindow(this);
                player.stop();
                //this.setExtendedState(JFrame.MAXIMIZED_BOTH);
                this.setVisible(true);
                
                initVlcLibAndPlayer();
                if (f != null) {
                    player.playMedia(f.getAbsolutePath());
                    player.setTime(time);
                }
                
            } else {
                jLayeredPane1.setVisible(true);
                LayerPlayAnBtn.setVisible(true);
                this.dispose();
                b=false;                
                this.setUndecorated(false);
                //this.pack();
                
                this.setVisible(true);
                player.setFullScreen(false);
                if (f != null) {
                    initVlcLibAndPlayer();
                    player.playMedia(f.getAbsolutePath());
                    player.setTime(time);
                }
                

           }
           
            
        }
            
    }//GEN-LAST:event_canvas1MouseClicked

//    boolean isDragging=false;
//    int dragIndex;
    private void ListSongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListSongMouseClicked

    }//GEN-LAST:event_ListSongMouseClicked

    private void ListSongMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListSongMouseMoved
        //        if(isDragging==true){
            //            int dropIndex=ListSong.locationToIndex(evt.getPoint());
            //            if(dragIndex!=dropIndex){
                //                mod.add(dropIndex, mod.remove(dragIndex));
                //            }
            //            isDragging=false;
            //        }
    }//GEN-LAST:event_ListSongMouseMoved

    //boolean mouseDragging;
    private void ListSongMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListSongMouseDragged
        //        isDragging=true;
        //        dragIndex=ListSong.getSelectedIndex();
    }//GEN-LAST:event_ListSongMouseDragged

    private void btnAddSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSongActionPerformed
        JFileChooser fc=new JFileChooser();
        int a=fc.showOpenDialog(null);
        if(a==JFileChooser.APPROVE_OPTION){
            File f=fc.getSelectedFile();
            mod.addElement(f.getName());
            arraySong.add(f);

        }

    }//GEN-LAST:event_btnAddSongActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        try {
            f=arraySong.get(0);
            player.playMedia(f.getAbsolutePath());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnPlayActionPerformed

    private void LayerPlayAnBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LayerPlayAnBtnMouseEntered
        jDesktopPane2.setVisible(true);
    }//GEN-LAST:event_LayerPlayAnBtnMouseEntered

    private void SlicePlayingMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SlicePlayingMouseDragged
        player.setTime(SlicePlaying.getValue());
    }//GEN-LAST:event_SlicePlayingMouseDragged

    private void SlicePlayingMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SlicePlayingMouseReleased
        player.setTime(SlicePlaying.getValue());
    }//GEN-LAST:event_SlicePlayingMouseReleased

    Runnable r=new Runnable() {
        @Override
        public void run() {
            LayerPlayAnBtn.setVisible(true);
            try {
                Thread.sleep(2000);
            } catch (Exception e) {
            }
            LayerPlayAnBtn.setVisible(false);
            
        }
    };
    Thread th;
    private void canvas1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvas1MouseMoved
        if(!LayerPlayAnBtn.isVisible()){
            th=new Thread(r);
            th.start();
        }
            
    }//GEN-LAST:event_canvas1MouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VideoPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VideoPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VideoPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VideoPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VideoPlayer().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane LayerPlayAnBtn;
    private javax.swing.JList<String> ListSong;
    private javax.swing.JSlider SlicePlaying;
    private javax.swing.JSlider SlideVolumn;
    private javax.swing.JButton btnAddSong;
    private javax.swing.JButton btnLeft;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnRight;
    private javax.swing.JButton btnStereo;
    private java.awt.Canvas canvas1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
